### ISSUE TITLE
Doesn't include headers in txt or HTML

### ISSUE THREAD

**Issue by nogweii** [worlddb/world.db.starter#1]
Just something I felt was missing in the alternative forms. :)

**Comment by geraldb** [comment]
@evaryont  FYI It happened ;-)  Headers are now included in csv and html tables e.g.

```
key,title,code,pop,area,synonyms
ad,Andorra,AND,85082,468,
ae,United Arab Emirates,UAE,8264070,83600,
```

The support is generic e.g. handled by the new webservice gem / library. Cheers.

**Comment by nogweii** [comment]
Ah! I had forgotten about this issue. Thanks for coming back to it!
